services:
  db:
    image: postgres:16
    ports:
      - 5434:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - mangdiman

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - PORT
      - ACCESS_KEY_ID
      - SECRET_ACCESS_KEY
      - ENDPOINT
      - TOKEN_VALUE
      - BASE_URL
    command: sh -c "yarn prisma:dev:deploy && yarn seed && yarn tailwind:dev & yarn start:dev"

networks:
  mangdiman: